<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitasQuirurgicasTableSeeder extends Seeder
{
    public function run(): void
    {
        $citas = [
            [
                'ci_paciente' => 123456789,
                'fecha' => '2024-03-15',
                'hora_inicio_estimada' => '08:00:00',
                'hora_inicio_real' => null,
                'hora_fin_real' => null,
                'ci_cirujano' => 12345678,
                'ci_instrumentista' => 23456789,
                'ci_anestesiologo' => 34567890,
                'tipo_cirugia' => 'menor',
                'tipo_final' => null,
                'descripcion_cirugia' => 'Apendicectomía laparoscópica',
                'nro_quirofano' => 1,
                'estado' => 'programada',
                'timestamp_inicio' => null,
                'timestamp_fin' => null,
                'costo_base' => 800.00,
                'costo_final' => null,
                'costo_minuto_extra' => 15.00,
                'observaciones' => 'Paciente preparado',
                'motivo_cancelacion' => null,
                'id_usuario_registro' => 1
            ],
            [
                'ci_paciente' => 234567890,
                'fecha' => '2024-03-15',
                'hora_inicio_estimada' => '10:30:00',
                'hora_inicio_real' => null,
                'hora_fin_real' => null,
                'ci_cirujano' => 45678901,
                'ci_instrumentista' => 56789012,
                'ci_anestesiologo' => 67890123,
                'tipo_cirugia' => 'mediana',
                'tipo_final' => null,
                'descripcion_cirugia' => 'Colecistectomía laparoscópica',
                'nro_quirofano' => 2,
                'estado' => 'programada',
                'timestamp_inicio' => null,
                'timestamp_fin' => null,
                'costo_base' => 1200.00,
                'costo_final' => null,
                'costo_minuto_extra' => 20.00,
                'observaciones' => 'Estudios preoperatorios completos',
                'motivo_cancelacion' => null,
                'id_usuario_registro' => 1
            ],
            [
                'ci_paciente' => 345678901,
                'fecha' => '2024-03-15',
                'hora_inicio_estimada' => '14:00:00',
                'hora_inicio_real' => null,
                'hora_fin_real' => null,
                'ci_cirujano' => 78901234,
                'ci_instrumentista' => 89012345,
                'ci_anestesiologo' => 90123456,
                'tipo_cirugia' => 'mayor',
                'tipo_final' => null,
                'descripcion_cirugia' => 'Reparación de hernia diafragmática',
                'nro_quirofano' => 3,
                'estado' => 'programada',
                'timestamp_inicio' => null,
                'timestamp_fin' => null,
                'costo_base' => 1500.00,
                'costo_final' => null,
                'costo_minuto_extra' => 25.00,
                'observaciones' => 'Equipo completo disponible',
                'motivo_cancelacion' => null,
                'id_usuario_registro' => 1
            ],
            [
                'ci_paciente' => 456789012,
                'fecha' => '2024-03-15',
                'hora_inicio_estimada' => '16:30:00',
                'hora_inicio_real' => null,
                'hora_fin_real' => null,
                'ci_cirujano' => 11223344,
                'ci_instrumentista' => 22334455,
                'ci_anestesiologo' => 33445566,
                'tipo_cirugia' => 'ambulatoria',
                'tipo_final' => null,
                'descripcion_cirugia' => 'Ligadura de trompas',
                'nro_quirofano' => 4,
                'estado' => 'programada',
                'timestamp_inicio' => null,
                'timestamp_fin' => null,
                'costo_base' => 600.00,
                'costo_final' => null,
                'costo_minuto_extra' => 10.00,
                'observaciones' => 'Alta prevista el mismo día',
                'motivo_cancelacion' => null,
                'id_usuario_registro' => 1
            ],
            [
                'ci_paciente' => 567890123,
                'fecha' => '2024-03-16',
                'hora_inicio_estimada' => '08:30:00',
                'hora_inicio_real' => null,
                'hora_fin_real' => null,
                'ci_cirujano' => 44556677,
                'ci_instrumentista' => 55667788,
                'ci_anestesiologo' => 66778899,
                'tipo_cirugia' => 'menor',
                'tipo_final' => null,
                'descripcion_cirugia' => 'Circuncisión',
                'nro_quirofano' => 1,
                'estado' => 'programada',
                'timestamp_inicio' => null,
                'timestamp_fin' => null,
                'costo_base' => 500.00,
                'costo_final' => null,
                'costo_minuto_extra' => 10.00,
                'observaciones' => 'Cirugía pediátrica',
                'motivo_cancelacion' => null,
                'id_usuario_registro' => 1
            ],
            [
                'ci_paciente' => 678901234,
                'fecha' => '2024-03-16',
                'hora_inicio_estimada' => '11:00:00',
                'hora_inicio_real' => null,
                'hora_fin_real' => null,
                'ci_cirujano' => 77889900,
                'ci_instrumentista' => 88990011,
                'ci_anestesiologo' => 99001122,
                'tipo_cirugia' => 'mediana',
                'tipo_final' => null,
                'descripcion_cirugia' => 'Artroscopia de rodilla',
                'nro_quirofano' => 2,
                'estado' => 'programada',
                'timestamp_inicio' => null,
                'timestamp_fin' => null,
                'costo_base' => 1000.00,
                'costo_final' => null,
                'costo_minuto_extra' => 18.00,
                'observaciones' => 'Equipo artroscópico reservado',
                'motivo_cancelacion' => null,
                'id_usuario_registro' => 1
            ],
            [
                'ci_paciente' => 789012345,
                'fecha' => '2024-03-16',
                'hora_inicio_estimada' => '14:30:00',
                'hora_inicio_real' => null,
                'hora_fin_real' => null,
                'ci_cirujano' => 11223344,
                'ci_instrumentista' => 22334455,
                'ci_anestesiologo' => 33445566,
                'tipo_cirugia' => 'mayor',
                'tipo_final' => null,
                'descripcion_cirugia' => 'Mastectomía parcial',
                'nro_quirofano' => 3,
                'estado' => 'programada',
                'timestamp_inicio' => null,
                'timestamp_fin' => null,
                'costo_base' => 1800.00,
                'costo_final' => null,
                'costo_minuto_extra' => 30.00,
                'observaciones' => 'Biopsia intraoperatoria programada',
                'motivo_cancelacion' => null,
                'id_usuario_registro' => 1
            ],
            [
                'ci_paciente' => 890123456,
                'fecha' => '2024-03-16',
                'hora_inicio_estimada' => '17:00:00',
                'hora_inicio_real' => null,
                'hora_fin_real' => null,
                'ci_cirujano' => 44556677,
                'ci_instrumentista' => 55667788,
                'ci_anestesiologo' => 66778899,
                'tipo_cirugia' => 'ambulatoria',
                'tipo_final' => null,
                'descripcion_cirugia' => 'Sinuscopy endoscópica',
                'nro_quirofano' => 4,
                'estado' => 'programada',
                'timestamp_inicio' => null,
                'timestamp_fin' => null,
                'costo_base' => 400.00,
                'costo_final' => null,
                'costo_minuto_extra' => 8.00,
                'observaciones' => 'Cirugía otorrinolaringológica',
                'motivo_cancelacion' => null,
                'id_usuario_registro' => 1
            ],
            [
                'ci_paciente' => 901234567,
                'fecha' => '2024-03-14',
                'hora_inicio_estimada' => '09:00:00',
                'hora_inicio_real' => '09:15:00',
                'hora_fin_real' => '10:45:00',
                'ci_cirujano' => 12345678,
                'ci_instrumentista' => 23456789,
                'ci_anestesiologo' => 34567890,
                'tipo_cirugia' => 'menor',
                'tipo_final' => 'menor',
                'descripcion_cirugia' => 'Reducción de fractura',
                'nro_quirofano' => 5,
                'estado' => 'finalizada',
                'timestamp_inicio' => '2024-03-14 09:15:00',
                'timestamp_fin' => '2024-03-14 10:45:00',
                'costo_base' => 500.00,
                'costo_final' => 525.00,
                'costo_minuto_extra' => 10.00,
                'observaciones' => 'Cirugía exitosa sin complicaciones',
                'motivo_cancelacion' => null,
                'id_usuario_registro' => 1
            ],
            [
                'ci_paciente' => 112233445,
                'fecha' => '2024-03-14',
                'hora_inicio_estimada' => '13:00:00',
                'hora_inicio_real' => null,
                'hora_fin_real' => null,
                'ci_cirujano' => 45678901,
                'ci_instrumentista' => 56789012,
                'ci_anestesiologo' => 67890123,
                'tipo_cirugia' => 'mediana',
                'tipo_final' => null,
                'descripcion_cirugia' => 'Herniorrafia inguinal',
                'nro_quirofano' => 1,
                'estado' => 'cancelada',
                'timestamp_inicio' => null,
                'timestamp_fin' => null,
                'costo_base' => 800.00,
                'costo_final' => null,
                'costo_minuto_extra' => 15.00,
                'observaciones' => null,
                'motivo_cancelacion' => 'Paciente presentó fiebre',
                'id_usuario_registro' => 1
            ],
        ];

        DB::table('citas_quirurgicas')->insert($citas);
    }
}
