<?php

namespace Database\Seeders;

use App\Models\AlmacenCatalogo;
use App\Models\AlmacenLote;
use App\Models\AlmacenStock;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicamentosGeneralesSeeder extends Seeder
{
    public function run(): void
    {
        $fechaVencimiento = Carbon::now()->addYear()->format('Y-m-d');

        $medicamentos = array_merge(
            $this->getGenitourinarioHormonas(),
            $this->getDermatologicos(),
            $this->getOrganosSentidos(),
            $this->getHormonalesSistemicos(),
            $this->getAntiparasitarios(),
            $this->getCardiovascular(),
            $this->getDigestivoMetabolismo(),
            $this->getMusculoesqueletico(),
            $this->getSistemaNervioso(),
            $this->getSistemaRespiratorio(),
            $this->getVarios(),
            $this->getSangreHematopoyeticos()
        );

        $total = count($medicamentos);
        $creados = 0;

        foreach ($medicamentos as $med) {
            DB::transaction(function () use ($med, $fechaVencimiento, &$creados) {
                $catalogo = AlmacenCatalogo::create([
                    'nombre' => $med['nombre'],
                    'descripcion' => $med['descripcion'],
                    'unidad_medida' => $med['unidad_medida'],
                    'tipo' => 'medicamento',
                    'activo' => true,
                    'observaciones' => $med['observaciones'],
                ]);

                $lote = AlmacenLote::create([
                    'catalogo_id' => $catalogo->id,
                    'codigo_lote' => null,
                    'fecha_vencimiento' => $fechaVencimiento,
                    'precio_compra' => 0,
                    'porcentaje_ganancia' => 0,
                    'precio_venta' => 0,
                    'cantidad_inicial' => 0,
                ]);

                AlmacenStock::create([
                    'lote_id' => $lote->id,
                    'ubicacion' => 'central',
                    'cantidad_actual' => 0,
                    'stock_minimo' => 0,
                ]);

                $creados++;
            });
        }

        $this->command->info("Total de medicamentos generales creados: {$creados}/{$total}");
    }

    private function getGenitourinarioHormonas(): array
    {
        return [
            ['nombre' => 'Ácido acético (Ácido tricloroacético)', 'descripcion' => 'Solución tópica 50%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Bromocriptina', 'descripcion' => 'Comprimido 2,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Bromocriptina', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cabergolina', 'descripcion' => 'Comprimido 0,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciproterona acetato + Estradiol valerato', 'descripcion' => 'Comprimido 2 mg + 0,035 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciproterona acetato + Estradiol valerato', 'descripcion' => 'Comprimido 2 mg + 1 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clomifeno citrato', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clotrimazol', 'descripcion' => 'Crema vaginal 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Clotrimazol', 'descripcion' => 'Óvulo 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ergometrina maleato', 'descripcion' => 'Comprimido 0,2 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ergometrina maleato', 'descripcion' => 'Inyectable 0,2 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Estradiol + Noretisterona acetato', 'descripcion' => 'Comprimido 2mg + 1mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Estradiol valerianato + Norgestrel', 'descripcion' => 'Comprimido 2 mg + 0,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Estradiol valerianato + Prasterona enantato', 'descripcion' => 'Inyectable 4 mg + 200 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Estrógenos conjugados', 'descripcion' => 'Comprimido 0,625 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Estrógenos conjugados', 'descripcion' => 'Comprimido 1,25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Estrógenos conjugados', 'descripcion' => 'Crema vaginal 0,625 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Finasterida', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gonadotrofina coriónica', 'descripcion' => 'Inyectable 5.000 UI/ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Levonorgestrel', 'descripcion' => 'Comprimido 0,75 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Levonorgestrel', 'descripcion' => 'Comprimido 1,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Levonorgestrel', 'descripcion' => 'Implante subdérmico 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Levonorgestrel + Etinilestradiol', 'descripcion' => 'Comprimido 0,150 mg + 0,03 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Medroxiprogesterona acetato', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Medroxiprogesterona acetato', 'descripcion' => 'Inyectable 104mg/0,65 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Medroxiprogesterona acetato', 'descripcion' => 'Inyectable 150 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metronidazol', 'descripcion' => 'Óvulo 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mifepristona', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Misoprostol', 'descripcion' => 'Comprimido vaginal 25 mcg', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Nistatina', 'descripcion' => 'Óvulo 100.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Noretisterona', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Norgestrel + Etinilestradiol', 'descripcion' => 'Comprimido 0,3 mg + 0,03 mg ó 0,5 mg + 0,05 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Oxitocina', 'descripcion' => 'Inyectable 5 UI/ml o 10 UI/ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Progesterona', 'descripcion' => 'Cápsula 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ritodrina', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ritodrina', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Testosterona undecanoato', 'descripcion' => 'Inyectable 1.000 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }

    private function getDermatologicos(): array
    {
        return [
            ['nombre' => 'Aciclovir', 'descripcion' => 'Crema dérmica 5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Ácido salicílico', 'descripcion' => 'Solución tópica 5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Alcohol etílico (Etanol)', 'descripcion' => 'Solución 1 l 70% a 95%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Bacitracina + Neomicina sulfato', 'descripcion' => 'Crema o Pomada 500 UI + 5 mg/g', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Betametasona (valerato)', 'descripcion' => 'Crema o Pomada 0,1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Clobetasol', 'descripcion' => 'Crema o Pomada 0,05%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Clobetasol', 'descripcion' => 'Solución 0,05%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Clorhexidina gluconato', 'descripcion' => 'Solución N/A', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Clotrimazol', 'descripcion' => 'Crema o Pomada 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Eritromicina', 'descripcion' => 'Loción 2% a 4%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Eter alifático dietilamino etanol', 'descripcion' => 'Solución 1 l N/A', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Formaldehido', 'descripcion' => 'Solución 40% p/v', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Glicerol (Glicerina bidestilada)', 'descripcion' => 'Solución 1 l N/A', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Hidrocortisona acetato', 'descripcion' => 'Crema o Pomada 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Hidroquinona', 'descripcion' => 'Crema o Pomada 4% o 5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Hidroquinona', 'descripcion' => 'Loción 4% o 5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Hipoclorito de sodio', 'descripcion' => 'Solución 8%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Iodo (Yodo)', 'descripcion' => 'Solución hidroalcohólica 2%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Iodo povidona (Yodopovidona)', 'descripcion' => 'Crema o Pomada 10% (500 g)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Iodo povidona (Yodopovidona)', 'descripcion' => 'Solución 10%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Lidocaína', 'descripcion' => 'Gel o Jalea 2%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Lidocaína clorhidrato', 'descripcion' => 'Solución para atomización 10%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Nistatina', 'descripcion' => 'Crema o Pomada 100.000 UI/g', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Nitrofural (Nitrofurazona)', 'descripcion' => 'Crema o Pomada 0,2% (450 g)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Oxido de Zinc con o sin aceite', 'descripcion' => 'Pasta o Pomada N/A', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Peróxido de Benzoílo', 'descripcion' => 'Crema, Pomada o Gel 5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Peróxido de Benzoílo', 'descripcion' => 'Loción 5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Peróxido de hidrógeno (Agua oxigenada)', 'descripcion' => 'Solución 2% o 3%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Resina de Podofilo (Podofilina)', 'descripcion' => 'Solución tópica 10% o 25%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Resorcinol', 'descripcion' => 'Crema o Pomada 10%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Ritonavir', 'descripcion' => 'Cápsula blanda 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Sulfadiazina de plata', 'descripcion' => 'Crema o Pomada 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Terbinafina', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tiabendazol', 'descripcion' => 'Crema o Pomada 5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Tolnaftato', 'descripcion' => 'Solución 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Trolamina', 'descripcion' => 'Emulsión dérmica 0,67%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Ungüento dérmico eucalipto mentol', 'descripcion' => 'Ungüento o crema N/A', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Vaselina líquida', 'descripcion' => 'Solución 1 l N/A', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Vaselina sólida', 'descripcion' => 'Pasta 1 kg N/A', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Violeta de genciana (Cloruro de metilrosanilina)', 'descripcion' => 'Solución 1%', 'unidad_medida' => '%', 'observaciones' => null],
        ];
    }

    private function getOrganosSentidos(): array
    {
        return [
            ['nombre' => 'Aciclovir', 'descripcion' => 'Crema o Pomada oftálmica 3%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Atropina sulfato', 'descripcion' => 'Solución oftálmica 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Ciclosporina', 'descripcion' => 'Solución oftálmica 0,1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Ciprofloxacina', 'descripcion' => 'Solución oftálmica 0,3%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Cloranfenicol', 'descripcion' => 'Solución oftálmica 0,5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Cloranfenicol', 'descripcion' => 'Ungüento oftálmico 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Corticoide + antiinfeccioso de acción tópica', 'descripcion' => 'Solución oftálmica Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Corticoide + antiinfeccioso de acción tópica', 'descripcion' => 'Ungüento oftálmico Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Dexametasona', 'descripcion' => 'Solución oftálmica 0,1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Dexametasona', 'descripcion' => 'Ungüento o Pomada oftálmica 0,1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Diclofenaco Sódico', 'descripcion' => 'Solución oftálmica 0,1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Dorzolamida', 'descripcion' => 'Solución oftálmica 2%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Fluoresceina', 'descripcion' => 'Inyectable 10%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Fluoresceina (sal sódica)', 'descripcion' => 'Solución oftálmica 0,25%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Gentamicina', 'descripcion' => 'Solución oftálmica 0,3%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Gentamicina', 'descripcion' => 'Ungüento oftálmico 0,3%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Glicerina + carbonato de sodio', 'descripcion' => 'Gotas óticas Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Ketotifeno', 'descripcion' => 'Solución oftálmica 0,25 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lágrimas artificiales', 'descripcion' => 'Gel 0,3% o 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Lágrimas artificiales', 'descripcion' => 'Solución oftálmica 0,3% o 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Latanoprost', 'descripcion' => 'Solución oftálmica 50 mcg/ml', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Nafazolina clorhidrato', 'descripcion' => 'Solución oftálmica 0,1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Proximetacaina (Proparacaina)', 'descripcion' => 'Solución oftálmica 0,5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución Fisiológica', 'descripcion' => 'Solución Nasal 0,9% (15 a 30 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Timolol maleato', 'descripcion' => 'Solución oftálmica 0,5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Tropicamida', 'descripcion' => 'Solución oftálmica 1%', 'unidad_medida' => '%', 'observaciones' => null],
        ];
    }

    private function getHormonalesSistemicos(): array
    {
        return [
            ['nombre' => 'Betametasona (fosfato)', 'descripcion' => 'Inyectable 4 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Carbetocina', 'descripcion' => 'Inyectable 100 mcg/ml', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Corticotrofina (ACTH)', 'descripcion' => 'Inyectable 25 UI o 40 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Desmopresina acetato', 'descripcion' => 'Solución nasal 0,1 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dexametasona', 'descripcion' => 'Comprimido 0,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dexametasona', 'descripcion' => 'Comprimido 4 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dexametasona', 'descripcion' => 'Inyectable 4 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Hidrocortisona succinato sódico', 'descripcion' => 'Inyectable 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Hidrocortisona succinato sódico', 'descripcion' => 'Inyectable 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Levotiroxina sódica', 'descripcion' => 'Comprimido 0,05 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Levotiroxina sódica', 'descripcion' => 'Comprimido ranurado 0,1 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metilprednisolona succinato sódico', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Prednisona', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Prednisona', 'descripcion' => 'Comprimido ranurado 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Prednisona', 'descripcion' => 'Suspensión 1 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Propiltiouracilo', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Somatropina', 'descripcion' => 'Inyectable 4UI (1,33 mg)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Terlipresina', 'descripcion' => 'Inyectable 1 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tiamazol (Metimazol)', 'descripcion' => 'Comprimido 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }

    private function getAntiparasitarios(): array
    {
        return [
            ['nombre' => 'Albendazol', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Albendazol', 'descripcion' => 'Suspensión 200 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Artemeter + Lumefantrina', 'descripcion' => 'Comprimido 20 mg + 120 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Artesunato', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Artesunato', 'descripcion' => 'Inyectable 60 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Artesunato + Mefloquina', 'descripcion' => 'Comprimido 100 mg + 220 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Artesunato + Mefloquina', 'descripcion' => 'Comprimido 25 mg + 55 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Benznidazol', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Benznidazol', 'descripcion' => 'Comprimido 12,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Benznidazol', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Benzoato de bencilo', 'descripcion' => 'Solución o Loción 20% o 25%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Cloroquina fosfato', 'descripcion' => 'Comprimido 250 mg (150 mg base)', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Hidroxicloroquina sulfato', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ivermectina', 'descripcion' => 'Comprimido 3 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ivermectina', 'descripcion' => 'Comprimido 6 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mebendazol', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mebendazol', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mebendazol', 'descripcion' => 'Suspensión 100 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mefloquina (clorhidrato)', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Meglumina antimoniato', 'descripcion' => 'Inyectable 1,5 g/5 ml', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Metronidazol', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metronidazol', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metronidazol', 'descripcion' => 'Suspensión 125 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metronidazol', 'descripcion' => 'Suspensión 250 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Niclosamida', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nifurtimox', 'descripcion' => 'Comprimido 120 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nifurtimox', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nifurtimox', 'descripcion' => 'Comprimido 30 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nitazoxanida', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nitazoxanida', 'descripcion' => 'Jarabe 100 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pentamidina', 'descripcion' => 'Inyectable 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pentamidina', 'descripcion' => 'Inyectable 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Permetrina', 'descripcion' => 'Crema o Pomada 5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Permetrina', 'descripcion' => 'Loción 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Pirantel pamoato', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pirantel pamoato', 'descripcion' => 'Suspensión 250 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pirimetamina', 'descripcion' => 'Comprimido 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Prazicuantel', 'descripcion' => 'Comprimido 600 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Primaquina (base)', 'descripcion' => 'Comprimido 15 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Primaquina (base)', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Primaquina (base)', 'descripcion' => 'Suspensión 15 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Quinina (bisulfato o sulfato)', 'descripcion' => 'Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Quinina (diclorhidrato)', 'descripcion' => 'Inyectable 600 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Sulfadoxina + Pirimetamina', 'descripcion' => 'Comprimido 500 mg + 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tiabendazol', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tiabendazol', 'descripcion' => 'Suspensión 500 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Triclabendazol', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }

    private function getCardiovascular(): array
    {
        return [
            ['nombre' => 'Acetazolamida', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Adenosina', 'descripcion' => 'Inyectable 6 mg/2 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amiodarona (clorhidrato)', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amiodarona (clorhidrato)', 'descripcion' => 'Inyectable 50 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amlodipina', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Atenolol', 'descripcion' => 'Comprimido ranurado 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Atorvastatina', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Atorvastatina', 'descripcion' => 'Comprimido 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Bisoprolol', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Carvedilol', 'descripcion' => 'Comprimido 12,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Carvedilol', 'descripcion' => 'Comprimido 6,25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Corticoide + anestésico', 'descripcion' => 'Crema o Pomada Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Corticoide + anestésico', 'descripcion' => 'Supositorio Según disponibilidad', 'unidad_medida' => 'unidades', 'observaciones' => null],
            ['nombre' => 'Digoxina', 'descripcion' => 'Comprimido ranurado 0,25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Digoxina', 'descripcion' => 'Inyectable 0,25 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Digoxina', 'descripcion' => 'Solución oral gotas 0,75 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dinitrato de isosorbida (Isosorbide dinitrato)', 'descripcion' => 'Comprimido sublingual 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dobutamina clorhidrato', 'descripcion' => 'Inyectable 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dopamina clorhidrato', 'descripcion' => 'Inyectable 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Enalapril maleato', 'descripcion' => 'Comprimido ranurado 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Epinefrina (Adrenalina)', 'descripcion' => 'Inyectable 1 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Espironolactona', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Espironolactona', 'descripcion' => 'Comprimido 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Etilefrina', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fenofibrato', 'descripcion' => 'Cápsula o Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Furosemida', 'descripcion' => 'Comprimido ranurado 40 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Furosemida', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gemfibrozilo', 'descripcion' => 'Comprimido 600 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Hidralazina clorhidrato', 'descripcion' => 'Comprimido 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Hidralazina clorhidrato', 'descripcion' => 'Inyectable 20 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Hidroclorotiazida', 'descripcion' => 'Comprimido ranurado 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Hidroclorotiazida + Amilorida', 'descripcion' => 'Comprimido 50 mg + 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ibuprofeno', 'descripcion' => 'Inyectable 5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Isosorbida Mononitrato', 'descripcion' => 'Comprimido 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Labetalol', 'descripcion' => 'Inyectable 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Losartán', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metildopa (Alfametildopa)', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Milrinona', 'descripcion' => 'Inyectable 1 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nifedipino', 'descripcion' => 'Comprimido o Cápsula 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nimodipina', 'descripcion' => 'Comprimido 30 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nimodipina', 'descripcion' => 'Inyectable 0,2 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nitroglicerina (Trinitrato de glicerol)', 'descripcion' => 'Inyectable 5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nitroprusiato de sodio', 'descripcion' => 'Inyectable 25 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Noradrenalina', 'descripcion' => 'Inyectable 1 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Propranolol', 'descripcion' => 'Comprimido 40 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Propranolol', 'descripcion' => 'Inyectable 1 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rosuvastatina', 'descripcion' => 'Comprimido 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Sildenafilo', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Verapamilo', 'descripcion' => 'Comprimido 40 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Verapamilo', 'descripcion' => 'Comprimido 80 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Verapamilo', 'descripcion' => 'Inyectable 2,5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }

    private function getDigestivoMetabolismo(): array
    {
        return [
            ['nombre' => 'Aceite mineral', 'descripcion' => 'Emulsión oral 40%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Aceite vitaminado (alimento)', 'descripcion' => 'Emulsión oral Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Ácido Ascorbico (Vitamina C)', 'descripcion' => 'Inyectable 500 mg/ml (2 ml)', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido Ascorbico (Vitamina C)', 'descripcion' => 'Solución oral gotas Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Ácido Ursodeoxicólico', 'descripcion' => 'Cápsula 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Atropina sulfato', 'descripcion' => 'Inyectable 1 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Bicarbonato de sodio', 'descripcion' => 'Polvo 20 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Bisacodilo', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Butilbromuro de Hioscina (Butilescopolamina)', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Butilbromuro de Hioscina (Butilescopolamina)', 'descripcion' => 'Inyectable 20 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Butilbromuro de Hioscina (Butilescopolamina)', 'descripcion' => 'Solución oral gotas 0,1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Calcio (carbonato o citrato)', 'descripcion' => 'Comprimido 500 mg (ión calcio)', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Carbón medicinal activado', 'descripcion' => 'Polvo Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Cianocobalamina (Vitamina B12)', 'descripcion' => 'Inyectable 1 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cloruro de potasio', 'descripcion' => 'Solución oral 1,3 mEq/ml', 'unidad_medida' => 'mEq', 'observaciones' => null],
            ['nombre' => 'Colecalciferol (Vitamina D3)', 'descripcion' => 'Comprimido o Cápsula blanda 0,25 mcg', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Complejo B (B1 + B6 + B12)', 'descripcion' => 'Comprimido Según concentración estándar', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Complejo B (B1 + B6 + B12)', 'descripcion' => 'Inyectable Según concentración estándar', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Complejo de vitaminas y minerales (Uso pediatría) CMV', 'descripcion' => 'Polvo para solución oral Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Domperidona', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Enzimas pancreáticas (Lipasa, Proteasa y Amilasa en combinación)', 'descripcion' => 'Comprimido Según disponibilidad', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fibra natural', 'descripcion' => 'Polvo o granulado Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Fluoruro de sodio', 'descripcion' => 'Gel o Pasta Según Programa', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Fluoruro de sodio', 'descripcion' => 'Solución oral gotas 0,2%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Glibenclamida', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Glicerol (Glicerina)', 'descripcion' => 'Supositorio 1 g a 1,80 g (infantil)', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Glicerol (Glicerina)', 'descripcion' => 'Supositorio 2 g a 4 g (adulto)', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Hidróxido de aluminio y magnesio', 'descripcion' => 'Suspensión 1:1', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Insulina Glargina', 'descripcion' => 'Inyectable 100 U.I/ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Insulina Glulisina', 'descripcion' => 'Inyectable 100 U.I/ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Insulina recombinante humana NPH', 'descripcion' => 'Inyectable 100 UI/ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Insulina zinc cristalina recombinante humana', 'descripcion' => 'Inyectable 100 UI/ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Lactulosa', 'descripcion' => 'Solución oral 65% a 67%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Loperamida', 'descripcion' => 'Cápsula o Comprimido 2 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mesalazina', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mesalazina', 'descripcion' => 'Supositorio 1g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Metformina', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metformina', 'descripcion' => 'Comprimido 850 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metoclopramida', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metoclopramida', 'descripcion' => 'Inyectable 10mg/2ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metoclopramida', 'descripcion' => 'Solución para gotas orales 0,35% o 0,5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Misoprostol', 'descripcion' => 'Comprimido 200 mcg', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Multivitaminas', 'descripcion' => 'Comprimido Según concentración estándar', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Multivitaminas', 'descripcion' => 'Jarabe Según concentración estándar', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Multivitaminas', 'descripcion' => 'Polvo liofilizado Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Nistatina', 'descripcion' => 'Comprimido 500.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Nistatina', 'descripcion' => 'Suspensión 500.000 UI/5 ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Omeprazol', 'descripcion' => 'Cápsula 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Omeprazol', 'descripcion' => 'Inyectable 40 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ondansetrón', 'descripcion' => 'Comprimido 8 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ondansetrón', 'descripcion' => 'Inyectable 8 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Piridoxina clorhidrato (Vitamina B6)', 'descripcion' => 'Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Piridoxina clorhidrato (Vitamina B6)', 'descripcion' => 'Inyectable 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Propinoxato', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Propinoxato', 'descripcion' => 'Inyectable 5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ranitidina', 'descripcion' => 'Comprimido 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ranitidina', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Retinol (Vitamina A)', 'descripcion' => 'Cápsula o Perla 10.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Retinol (Vitamina A)', 'descripcion' => 'Cápsula o Perla 100.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Retinol (Vitamina A)', 'descripcion' => 'Cápsula o Perla 200.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Retinol (Vitamina A)', 'descripcion' => 'Cápsula o Perla 25.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Sales de rehidratación oral (SRO) baja osmolaridad', 'descripcion' => 'Sobres Según concentración estándar', 'unidad_medida' => 'unidades', 'observaciones' => null],
            ['nombre' => 'Simeticona', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Simeticona', 'descripcion' => 'Suspensión 3% o 4%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Sucralfato', 'descripcion' => 'Suspensión 1g/5 ml', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Sulfato de Magnesio', 'descripcion' => 'Granulado 20 g a 30 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Tiamina (Vitamina B 1)', 'descripcion' => 'Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tiamina (Vitamina B 1)', 'descripcion' => 'Inyectable 100 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tocoferol (Vitamina E)', 'descripcion' => 'Cápsula blanda 1.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Zinc (como sulfato)', 'descripcion' => 'Comprimido 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Zinc (como sulfato)', 'descripcion' => 'Jarabe 20 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }

    private function getMusculoesqueletico(): array
    {
        return [
            ['nombre' => 'Ácido Alendrónico (Alendronato)', 'descripcion' => 'Comprimido 70 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido Zoledrónico', 'descripcion' => 'Inyectable 4 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Alopurinol', 'descripcion' => 'Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Atracurio besilato', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Colchicina', 'descripcion' => 'Comprimido 0,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Diclofenaco Sódico', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Diclofenaco Sódico', 'descripcion' => 'Inyectable 75 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Diclofenaco Sódico', 'descripcion' => 'Pomada o Gel 1%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Ibuprofeno', 'descripcion' => 'Comprimido 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ibuprofeno', 'descripcion' => 'Suspensión 100 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Indometacina', 'descripcion' => 'Cápsula o Comprimido 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Indometacina', 'descripcion' => 'Supositorio 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ketoprofeno', 'descripcion' => 'Inyectable 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ketorolaco', 'descripcion' => 'Inyectable 30 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Meloxicam', 'descripcion' => 'Comprimido 15 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mivacuronio', 'descripcion' => 'Inyectable 2 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Penicilamina', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rocuronio bromuro', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Suxametonio (Succinil colina)', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }

    private function getSistemaNervioso(): array
    {
        return [
            ['nombre' => 'Ácido acetil salicílico', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido Valpróico ó Valproato sódico', 'descripcion' => 'Cápsula o Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido Valpróico ó Valproato sódico', 'descripcion' => 'Jarabe o Solución oral 200 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido Valpróico ó Valproato sódico', 'descripcion' => 'Jarabe o Solución oral 250 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Alprazolam', 'descripcion' => 'Comprimido ranurado 0,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amitriptilina', 'descripcion' => 'Comprimido ranurado 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Aripiprazol', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Aripiprazol', 'descripcion' => 'Comprimido 15 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Biperideno clorhidrato', 'descripcion' => 'Comprimido 4 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Bupivacaina clorhidrato', 'descripcion' => 'Inyectable 0,5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Bupivacaina clorhidrato (pesada)', 'descripcion' => 'Inyectable 0,5%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Bupivacaina clorhidrato con Epinefrina sin conservante', 'descripcion' => 'Inyectable 0,5% 1:200.000', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Cafeína Citrato', 'descripcion' => 'Inyectable 20 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Carbamazepina', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Carbamazepina', 'descripcion' => 'Suspensión o Jarabe 2% (100 mg/5 ml)', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clomipramina', 'descripcion' => 'Comprimido 75 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clomipramina (clorhidrato)', 'descripcion' => 'Inyectable 25 mg/2 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clonazepam', 'descripcion' => 'Comprimido ranurado 2 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clonazepam', 'descripcion' => 'Solución oral 2,5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clorpromazina', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clorpromazina', 'descripcion' => 'Inyectable 12,5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Codeína', 'descripcion' => 'Comprimido 30 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dexmedetomidina', 'descripcion' => 'Inyectable 100 mcg/ml', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Diazepam', 'descripcion' => 'Comprimido ranurado 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Diazepam', 'descripcion' => 'Comprimido ranurado 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Diazepam', 'descripcion' => 'Inyectable 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dimenhidrinato', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dimenhidrinato', 'descripcion' => 'Inyectable 50 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dimenhidrinato', 'descripcion' => 'Supositorio 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Droperidol', 'descripcion' => 'Inyectable 2,5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Duloxetina', 'descripcion' => 'Cápsula 30 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ergotamina tartrato + Cafeína', 'descripcion' => 'Comprimido 1 mg + 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fenitoína', 'descripcion' => 'Cápsula o Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fenitoína', 'descripcion' => 'Inyectable 50 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fenobarbital', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fenobarbital', 'descripcion' => 'Gotas 20 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fenobarbital', 'descripcion' => 'Inyectable 100 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fentanilo con conservante', 'descripcion' => 'Inyectable 0,05 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fentanilo sin conservante', 'descripcion' => 'Inyectable 0,05 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Flunarizina', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fluoxetina', 'descripcion' => 'Cápsula o Comprimido 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Haloperidol', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Haloperidol', 'descripcion' => 'Inyectable 5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Haloperidol', 'descripcion' => 'Solución oral 2 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Haloperidol decanoato', 'descripcion' => 'Inyectable 50 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Halotano', 'descripcion' => 'Solución 0,01% de timol', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Imipramina clorhidrato', 'descripcion' => 'Comprimido 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ketamina (Cetamina)', 'descripcion' => 'Inyectable 50 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lamotrigina', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lamotrigina', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lamotrigina', 'descripcion' => 'Comprimido 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lamotrigina', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Levodopa + Carbidopa', 'descripcion' => 'Comprimido 250 mg + 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lidocaína', 'descripcion' => 'Cartucho dental 2%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Lidocaína clorhidrato + Epinefrina', 'descripcion' => 'Cartucho dental 2% 1:200.000', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Lidocaína clorhidrato + Epinefrina', 'descripcion' => 'Inyectable 2% 1:200.000', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Lidocaína clorhidrato sin conservante', 'descripcion' => 'Inyectable 2%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Litio carbonato', 'descripcion' => 'Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metadona', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metamizol (Dipirona)', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Metilfenidato', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Midazolam', 'descripcion' => 'Inyectable 15 mg/3 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Morfina', 'descripcion' => 'Cápsula o Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Morfina (con y sin conservante)', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Naratriptan', 'descripcion' => 'Comprimido 2,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Neostigmina', 'descripcion' => 'Inyectable 0,5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Paracetamol (Acetaminofeno)', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Paracetamol (Acetaminofeno)', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Paracetamol (Acetaminofeno)', 'descripcion' => 'Gotas 100 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Paracetamol (Acetaminofeno)', 'descripcion' => 'Inyectable 1 gr', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Paracetamol (Acetaminofeno)', 'descripcion' => 'Jarabe 120 mg/5 ml o 125 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Paracetamol (Acetaminofeno)', 'descripcion' => 'Supositorio 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Petidina (Meperidina)', 'descripcion' => 'Inyectable 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Piridostigmina', 'descripcion' => 'Comprimido 60 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pregabalina', 'descripcion' => 'Comprimido o Cápsula 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pregabalina', 'descripcion' => 'Comprimido o Cápsula 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pregabalina', 'descripcion' => 'Comprimido o Cápsula 75 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Propofol', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Quetiapina', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Remifentanilo', 'descripcion' => 'Inyectable 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Risperidona', 'descripcion' => 'Comprimido 3 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Sevoflurano (Trifluorometil etil)', 'descripcion' => 'Solución 250 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Tiopental sódico', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Tioridazina', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tioridazina', 'descripcion' => 'Suspensión 100 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tramadol', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tramadol', 'descripcion' => 'Inyectable 100 mg/2 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tramadol', 'descripcion' => 'Solución para gotas orales 100 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }

    private function getSistemaRespiratorio(): array
    {
        return [
            ['nombre' => 'Aminofilina', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Aminofilina', 'descripcion' => 'Inyectable 250 mg/10 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Antigripal (Paracetamol + Antihistamínico + Vasoconstrictor con o sin Cafeína)', 'descripcion' => 'Comprimido Según disponibilidad', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Beclometasona dipropionato', 'descripcion' => 'Aerosol 50 mcg/inhalación', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Budesonida', 'descripcion' => 'Aerosol 100 mcg', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Cetirizina', 'descripcion' => 'Cápsula o Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cetirizina', 'descripcion' => 'Jarabe 5 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clorfenamina (Clorfeniramina)', 'descripcion' => 'Comprimido 4 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clorfenamina (Clorfeniramina)', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clorfenamina (Clorfeniramina)', 'descripcion' => 'Jarabe 2 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Codeína', 'descripcion' => 'Jarabe 10 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dextrometorfano bromhidrato', 'descripcion' => 'Jarabe 10 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ipratropio bromuro', 'descripcion' => 'Aerosol 20 mcg/dosis', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Ketotifeno', 'descripcion' => 'Comprimido 1 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Montelukast', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Montelukast', 'descripcion' => 'Comprimido o Cápsula 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Salbutamol', 'descripcion' => 'Aerosol 0,1 mg/inhalación', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Salbutamol', 'descripcion' => 'Comprimido 4 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Salbutamol', 'descripcion' => 'Solución para nebulización 5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Salmeterol + Fluticasona', 'descripcion' => 'Aerosol 25 mcg + 125 mcg', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Surfactante pulmonar', 'descripcion' => 'Inyectable 25 a 35 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Teofilina', 'descripcion' => 'Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }

    private function getVarios(): array
    {
        return [
            ['nombre' => 'Acetil Cisteina', 'descripcion' => 'Inyectable 10%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Ácido Gadotérico', 'descripcion' => 'Inyectable 0.5 mmol/ml', 'unidad_medida' => 'mmol', 'observaciones' => null],
            ['nombre' => 'Alimentos Terapéutico Listo para Uso (ATLU)', 'descripcion' => 'Polvo, pasta o Granulado según disponibilidad Según concentración estándar', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Complemento nutricional', 'descripcion' => 'Polvo Según concentración estándar', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Complemento nutricional (Carmelo)', 'descripcion' => 'Polvo Según concentración estándar', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Complemento nutricional (Diabético)', 'descripcion' => 'Polvo Según concentración estándar', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Complemento nutricional (Nutri Mama con Cañahua, probiótico y Omega-3)', 'descripcion' => 'Polvo Según concentración estándar', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Complemento nutricional (Nutribebé)', 'descripcion' => 'Polvo Según concentración estándar', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Contraste iodado', 'descripcion' => 'Inyectable Según disponibilidad (10 ml)', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Contraste iodado', 'descripcion' => 'Inyectable Según disponibilidad (100 ml o 200 ml)', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Contraste iodado', 'descripcion' => 'Inyectable Según disponibilidad (50 ml)', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Deferoxamina mesilato', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dimercaprol (B.A.L.)', 'descripcion' => 'Inyectable 100 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Edetato sódico de calcio (EDTA)', 'descripcion' => 'Inyectable 20%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Flumazenil', 'descripcion' => 'Inyectable 0,5 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gadobutrol', 'descripcion' => 'Inyectable 604,72mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gadodiamida', 'descripcion' => 'Inyectable 287 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gadopentato de dimeglumina', 'descripcion' => 'Inyectable 469 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gadoversetamida', 'descripcion' => 'Inyectable 0.5 mmol/ml', 'unidad_medida' => 'mmol', 'observaciones' => null],
            ['nombre' => 'Ipecacuana', 'descripcion' => 'Jarabe 7%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Leucovorina', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Leucovorina (Folinato de calcio)', 'descripcion' => 'Comprimido 15 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Meglumina diatrizoato', 'descripcion' => 'Inyectable 70% o 76% (20 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Meglumina diatrizoato', 'descripcion' => 'Inyectable 70% o 76% (50 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Mesna (Mercapto etilsulfonato sódico)', 'descripcion' => 'Inyectable 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Naloxona', 'descripcion' => 'Inyectable 0,4 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Oxígeno', 'descripcion' => 'Gas 93% - 99%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Permanganato de potasio', 'descripcion' => 'Solución acuosa 1:10.000', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Pralidoxima', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Protamina Sulfato', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Proteínas para alimentación enteral (alimento)', 'descripcion' => 'Polvo Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Solución de preservación de órganos sólidos HTK', 'descripcion' => 'Solución Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Sulfato de Bario', 'descripcion' => 'Polvo para enema Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Sulfato de Bario', 'descripcion' => 'Suspensión Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
        ];
    }

    private function getSangreHematopoyeticos(): array
    {
        return [
            ['nombre' => 'Ácido acetil salicílico', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido aminocapróico', 'descripcion' => 'Inyectable 2g/10 ml', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Ácido fólico', 'descripcion' => 'Comprimido 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido Fólico', 'descripcion' => 'Comprimido 800 mcg', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Ácido Tranexámico', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido Tranexámico', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Agentes con gelatina', 'descripcion' => 'Solución parenteral de gran volúmen Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Agua para inyección', 'descripcion' => 'Inyectable 5 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Albúmina humana', 'descripcion' => 'Inyectable 20%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Aminoácidos', 'descripcion' => 'Solución parenteral de gran volúmen 10%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Bicarbonato de sodio', 'descripcion' => 'Inyectable 8%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Bicarbonato de sodio p/hemodiálisis', 'descripcion' => 'Polvo Frasco por 720 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Clopidogrel', 'descripcion' => 'Comprimido 75 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cloruro de potasio', 'descripcion' => 'Inyectable 20%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Dextrán 70', 'descripcion' => 'Solución parenteral de gran volúmen 6%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Emulsión de lípidos', 'descripcion' => 'Emulsión inyectable Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Eritropoyetina', 'descripcion' => 'Inyectable 10.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Eritropoyetina', 'descripcion' => 'Inyectable 2.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Eritropoyetina', 'descripcion' => 'Inyectable 4000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Estreptoquinasa', 'descripcion' => 'Inyectable 1.500.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Etamsilato', 'descripcion' => 'Inyectable 250 mg/2 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Factor IX de la coagulación', 'descripcion' => 'Inyectable 500 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Factor VIII de la coagulación', 'descripcion' => 'Inyectable 500 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Fibrinógeno humano', 'descripcion' => 'Inyectable 1g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Fitomenadiona (Vitamina K1)', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gluconato Cálcico (Calcio Gluconato)', 'descripcion' => 'Inyectable 10%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Heparina de bajo peso molecular', 'descripcion' => 'Inyectable Según disponibilidad', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Heparina sódica', 'descripcion' => 'Inyectable 5.000 UI/ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Hierro', 'descripcion' => 'Inyectable 100 mg - IM o IV', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Hierro (como bisglicina quelato)', 'descripcion' => 'Suspensión 30 mg/5 mL', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Micronutrientes (Vit. C + Vit A + Fe + Zn + Ac. Fólico) (Chispitas nutricionales)', 'descripcion' => 'Polvo Según concentración estándar', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Oligoelementos para nutricion parenteral', 'descripcion' => 'Solución parenteral de gran volúmen Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Rivaroxabán', 'descripcion' => 'Comprimido 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Solución ácida', 'descripcion' => 'Solución Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución Básica', 'descripcion' => 'Solución Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución de glucosa', 'descripcion' => 'Inyectable 50% (20 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución de glucosa', 'descripcion' => 'Solución parenteral 10% (250 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución de glucosa', 'descripcion' => 'Solución parenteral de gran volumen 10% (1.000 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución de glucosa', 'descripcion' => 'Solución parenteral de gran volumen 10% (500 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución de glucosa', 'descripcion' => 'Solución parenteral de gran volumen 5% (1.000 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución de glucosa', 'descripcion' => 'Solución parenteral de gran volumen 5% (500 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución de glucosa', 'descripcion' => 'Solución parenteral de gran volumen 50% (500 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución de Manitol', 'descripcion' => 'Solución parenteral de gran volumen 20% (500 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución Fisiológica', 'descripcion' => 'Solución parenteral 0,9% (100 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución Fisiológica', 'descripcion' => 'Solución parenteral 0,9% (150 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución Fisiológica', 'descripcion' => 'Solución parenteral de gran volumen 0,9% (1.000 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución Fisiológica', 'descripcion' => 'Solución parenteral de gran volumen 0,9% (500 ml)', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Solución glucosada clorurada', 'descripcion' => 'Solución parenteral de gran volumen 1.000 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución glucosada clorurada', 'descripcion' => 'Solución parenteral de gran volumen 500 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución para diálisis intraperitoneal (de acuerdo a composición apropiada)', 'descripcion' => 'Solución parenteral Según disponibilidad', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución para diálisis peritoneal I', 'descripcion' => 'Solución parenteral de gran volumen 1.000 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución para diálisis peritoneal II', 'descripcion' => 'Solución parenteral de gran volumen 1.000 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución ringer lactato', 'descripcion' => 'Solución parenteral de gran volumen 1.000 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución ringer lactato', 'descripcion' => 'Solución parenteral de gran volumen 500 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución ringer normal', 'descripcion' => 'Solución parenteral de gran volumen 1.000 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Solución ringer normal', 'descripcion' => 'Solución parenteral de gran volumen 500 ml', 'unidad_medida' => 'ml', 'observaciones' => null],
            ['nombre' => 'Sulfato de Magnesio', 'descripcion' => 'Inyectable 10%', 'unidad_medida' => '%', 'observaciones' => null],
            ['nombre' => 'Sulfato ferroso', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Sulfato ferroso', 'descripcion' => 'Solución oral 125 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Sulfato ferroso + Ac. Fólico + Vitamina C', 'descripcion' => 'Comprimido 200 mg + 0,5 mg + 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Sulfato ferroso + Ac. Fólico + Vitamina C', 'descripcion' => 'Solución oral 125 mg + 0,25 mg + 30 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tenecteplasa', 'descripcion' => 'Polvo para Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Warfarina', 'descripcion' => 'Comprimido ranurado 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }
}
