<?php

namespace Database\Seeders;

use App\Models\AlmacenCatalogo;
use App\Models\AlmacenLote;
use App\Models\AlmacenStock;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicamentosOncologicosAntiinfecciososSeeder extends Seeder
{
    public function run(): void
    {
        $fechaVencimiento = Carbon::now()->addYear()->format('Y-m-d');

        $medicamentos = $this->getMedicamentosData();
        $total = count($medicamentos);
        $creados = 0;

        foreach ($medicamentos as $med) {
            DB::transaction(function () use ($med, $fechaVencimiento, &$creados) {
                $catalogo = AlmacenCatalogo::create([
                    'nombre' => $med['nombre'],
                    'descripcion' => $med['descripcion'],
                    'unidad_medida' => $med['unidad_medida'],
                    'tipo' => 'medicamento',
                    'activo' => true,
                    'observaciones' => $med['observaciones'],
                ]);

                $lote = AlmacenLote::create([
                    'catalogo_id' => $catalogo->id,
                    'codigo_lote' => null,
                    'fecha_vencimiento' => $fechaVencimiento,
                    'precio_compra' => 0,
                    'porcentaje_ganancia' => 0,
                    'precio_venta' => 0,
                    'cantidad_inicial' => 0,
                ]);

                AlmacenStock::create([
                    'lote_id' => $lote->id,
                    'ubicacion' => 'central',
                    'cantidad_actual' => 0,
                    'stock_minimo' => 0,
                ]);

                $creados++;
            });
        }

        $this->command->info("Total de medicamentos creados: {$creados}/{$total}");
    }

    private function getMedicamentosData(): array
    {
        return [
            // === ANTINEOPLASICOS E INMUNOMODULADORES ===
            ['nombre' => 'Abiraterona Acetato', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Anastrozol', 'descripcion' => 'Comprimido 1 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Asparaginasa', 'descripcion' => 'Inyectable 10.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Azatioprina', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Azatioprina', 'descripcion' => 'Inyectable 20 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Basiliximab', 'descripcion' => 'Polvo para inyectable 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Bevacizumab', 'descripcion' => 'Inyectable 25 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Bicalutamida', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Bleomicina', 'descripcion' => 'Inyectable 15 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Bortezomib', 'descripcion' => 'Polvo para inyectable 3,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Busulfano', 'descripcion' => 'Comprimido 2 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Capecitabine', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Carboplatino', 'descripcion' => 'Inyectable 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Carboplatino', 'descripcion' => 'Inyectable 450 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciclofosfamida', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciclofosfamida', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Ciclofosfamida', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciclosporina', 'descripcion' => 'Cápsula blanda 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciclosporina', 'descripcion' => 'Cápsula blanda 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciclosporina', 'descripcion' => 'Cápsula blanda 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciclosporina', 'descripcion' => 'Solución oral 100 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciproterona (acetato)', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cisplatino', 'descripcion' => 'Inyectable 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cisplatino', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Citarabina', 'descripcion' => 'Inyectable 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Citarabina', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dacarbazina', 'descripcion' => 'Inyectable 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dactinomicina', 'descripcion' => 'Inyectable 0,5 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dasatinib', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dasatinib', 'descripcion' => 'Comprimido 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dasatinib', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dasatinib', 'descripcion' => 'Comprimido 70 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Daunorrubicina', 'descripcion' => 'Inyectable 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Docetaxel', 'descripcion' => 'Inyectable 40 mg/ml (2ml)', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Doxorrubicina liposomal pegilada', 'descripcion' => 'Inyectable 20 mg/10 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Doxorubicina clorhidrato (Adriamicina clorh.)', 'descripcion' => 'Inyectable 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Doxorubicina clorhidrato (Adriamicina clorh.)', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Enzalutamida', 'descripcion' => 'Cápsula 40 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Erlotinib', 'descripcion' => 'Comprimido 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Etopósido', 'descripcion' => 'Inyectable 100 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Filgrastrim', 'descripcion' => 'Inyectable 300 mcg/ml', 'unidad_medida' => 'mcg', 'observaciones' => null],
            ['nombre' => 'Fingolimod', 'descripcion' => 'Cápsula 0,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fludarabina', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fluorouracilo', 'descripcion' => 'Inyectable 500 mg/10 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Flutamida', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gemcitabina', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Gemcitabina', 'descripcion' => 'Inyectable 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Globulina Anti-timocito', 'descripcion' => 'Inyectable 250 mg/5ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Globulina Anti-timocito (conejo)', 'descripcion' => 'Inyectable 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Hidroxiurea', 'descripcion' => 'Cápsula 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ifosfamida', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Imatinib', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Imatinib', 'descripcion' => 'Comprimido 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Interferon alfa 2 b recombinante', 'descripcion' => 'Inyectable 10.000.000 UI con diluyente (1 ml)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Interferon alfa 2 b recombinante', 'descripcion' => 'Inyectable 3.000.000 UI con diluyente (1 ml)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Interferon beta', 'descripcion' => 'Inyectable 0,3 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Irinotecan', 'descripcion' => 'Inyectable 100 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Leflunomida', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Leflunomida', 'descripcion' => 'Comprimido 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lenalidomida', 'descripcion' => 'Cápsula 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lenalidomida', 'descripcion' => 'Cápsula 15 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lenalidomida', 'descripcion' => 'Cápsula 25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lenalidomida', 'descripcion' => 'Cápsula 5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Letrozol', 'descripcion' => 'Comprimido 2,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Leuprolide', 'descripcion' => 'Inyectable 7,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Melfalán', 'descripcion' => 'Comprimido 2 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Melfalán', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mercaptopurina', 'descripcion' => 'Comprimido ranurado 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metotrexato', 'descripcion' => 'Comprimido 2,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metotrexato', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Metotrexato', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Micofenolato de mofetilo', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Mitomicina', 'descripcion' => 'Inyectable 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nimotuzumab', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Oxaliplatino', 'descripcion' => 'Inyectable 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Oxaliplatino', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Paclitaxel', 'descripcion' => 'Inyectable 30 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Paclitaxel', 'descripcion' => 'Inyectable 300 mg/50 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pazopanib', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pegaspargasa', 'descripcion' => 'Plegable Frasco Vial 750 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Pertuzumab', 'descripcion' => 'Inyectable 420 mg/14 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rituximab', 'descripcion' => 'Inyectable 100 mg/10ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rituximab', 'descripcion' => 'Inyectable 500 mg/50 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tacrolimus', 'descripcion' => 'Cápsula 1 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Talidomida', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tamoxifeno', 'descripcion' => 'Comprimido 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Temozolomida', 'descripcion' => 'Cápsula 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Temozolomida', 'descripcion' => 'Cápsula 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Temozolomida', 'descripcion' => 'Cápsula 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Trastuzumab', 'descripcion' => 'Inyectable 440 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Trastuzumab', 'descripcion' => 'Inyectable 600 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Triptorelina', 'descripcion' => 'Inyectable 11,25 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Triptorelina', 'descripcion' => 'Inyectable 22,5 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Vinblastina', 'descripcion' => 'Inyectable 10 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Vincristina', 'descripcion' => 'Inyectable 1 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Vinorelbina', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],

            // === ANTIINFECCIOSOS ===
            ['nombre' => 'Abacavir', 'descripcion' => 'Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Aciclovir', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Aciclovir', 'descripcion' => 'Comprimido 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Aciclovir', 'descripcion' => 'Comprimido 800 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Aciclovir', 'descripcion' => 'Inyectable 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Aciclovir', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Aciclovir', 'descripcion' => 'Suspensión 200 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido nalidíxico', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido nalidíxico', 'descripcion' => 'Suspensión 125 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ácido nalidíxico', 'descripcion' => 'Suspensión 250 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Acido p-aminosalicílico', 'descripcion' => 'Polvo para solución oral 4 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Amfotericina B', 'descripcion' => 'Inyectable 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amikacina', 'descripcion' => 'Inyectable 500mg/2 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amoxicilina', 'descripcion' => 'Comprimido 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Amoxicilina', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amoxicilina', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Amoxicilina', 'descripcion' => 'Suspensión 500 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amoxicilina + inhibidor betalactamasa', 'descripcion' => 'Comprimido 500 mg + Según disponibilidad', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amoxicilina + inhibidor betalactamasa', 'descripcion' => 'Comprimido 875 mg + Según disponibilidad', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Amoxicilina + inhibidor betalactamasa', 'descripcion' => 'Inyectable 1 g + Según disponibilidad', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Amoxicilina + inhibidor betalactamasa', 'descripcion' => 'Suspensión 250 mg + Según disponibilidad', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ampicilina', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Antitóxina tetánica', 'descripcion' => 'Inyectable Norma PAI según disponibilidad', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Atazanavir (sulfato)', 'descripcion' => 'Cápsula o Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Atazanavir + Ritonavir', 'descripcion' => 'Cápsula o Comprimido 300 mg + 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Azitromicina', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Azitromicina', 'descripcion' => 'Suspensión 200 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Bedaquilina', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Bencilpenicilina benzatínica', 'descripcion' => 'Inyectable 1.200.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Bencilpenicilina benzatínica', 'descripcion' => 'Inyectable 2.400.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Bencilpenicilina benzatínica', 'descripcion' => 'Inyectable 600.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Bencilpenicilina procaínica', 'descripcion' => 'Inyectable 400.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Bencilpenicilina procaínica', 'descripcion' => 'Inyectable 800.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Bencilpenicilina sódica', 'descripcion' => 'Inyectable 1.000.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Bencilpenicilina sódica', 'descripcion' => 'Inyectable 30.000.000 UI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Capreomicina', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Cefazolina', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Cefepima', 'descripcion' => 'Inyectable 1g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Cefixima', 'descripcion' => 'Comprimido o Cápsula 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cefixima', 'descripcion' => 'Suspensión 100 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cefotaxima', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Cefradina', 'descripcion' => 'Cápsula o Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cefradina', 'descripcion' => 'Suspensión 250 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ceftazidima', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Ceftriaxona', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Cicloserina', 'descripcion' => 'Cápsula 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciprofloxacina', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciprofloxacina', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ciprofloxacina', 'descripcion' => 'Inyectable 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Claritromicina', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Claritromicina', 'descripcion' => 'Suspensión 250 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clindamicina', 'descripcion' => 'Cápsula o Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clindamicina', 'descripcion' => 'Inyectable 600 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clindamicina', 'descripcion' => 'Suspensión o Jarabe 75 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clofazimina', 'descripcion' => 'Cápsula 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Clofazimina', 'descripcion' => 'Cápsula 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cloranfenicol', 'descripcion' => 'Cápsula 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cloranfenicol succinato sódico', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Cloxacilina', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Cloxacilina', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Colistina', 'descripcion' => 'Inyectable 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cotrimoxazol (Sulfametoxazol + Trimetoprima)', 'descripcion' => 'Comprimido 100 mg + 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cotrimoxazol (Sulfametoxazol + Trimetoprima)', 'descripcion' => 'Comprimido 400 mg + 80 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cotrimoxazol (Sulfametoxazol + Trimetoprima)', 'descripcion' => 'Comprimido 800 mg + 160 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cotrimoxazol (Sulfametoxazol + Trimetoprima)', 'descripcion' => 'Inyectable 400 mg + 80 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cotrimoxazol (Sulfametoxazol + Trimetoprima)', 'descripcion' => 'Suspensión 200 mg + 40 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Cotrimoxazol (Sulfametoxazol + Trimetoprima)', 'descripcion' => 'Suspensión 400 mg + 80 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Daclatasvir', 'descripcion' => 'Cápsula o Comprimido 60 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dapsona', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dapsona', 'descripcion' => 'Comprimido 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Darunavir', 'descripcion' => 'Comprimido 600 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Delamanid', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dicloxacilina sódica', 'descripcion' => 'Cápsula 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Dicloxacilina sódica', 'descripcion' => 'Suspensión 250 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Doxiciclina', 'descripcion' => 'Cápsula o Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Efavirenz', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Efavirenz', 'descripcion' => 'Comprimido 600 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Eritromicina (estearato)', 'descripcion' => 'Cápsula o Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Eritromicina (etilsuccinato)', 'descripcion' => 'Suspensión 250 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Espiramicina', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Estreptomicina sulfato', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Etambutol', 'descripcion' => 'Comprimido 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Etionamida', 'descripcion' => 'Comprimido 250 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Favipiravir', 'descripcion' => 'Comprimido recubierto 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fluconazol', 'descripcion' => 'Comprimido o Cápsula 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Fluconazol', 'descripcion' => 'Inyectable 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gentamicina sulfato', 'descripcion' => 'Inyectable 20 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Gentamicina sulfato', 'descripcion' => 'Inyectable 80 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Griseofulvina', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Griseofulvina', 'descripcion' => 'Suspensión 125 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Imipenem + Cilastatina', 'descripcion' => 'Inyectable 500 mg + 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Inmunoglobulina anti D (RH +)', 'descripcion' => 'Inyectable 0,1 mg/ml a 0,2 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Inmunoglobulina humana normal', 'descripcion' => 'Inyectable 5 g IV', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Isoniazida (INH)', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Kanamicina', 'descripcion' => 'Inyectable 1 g', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Lamivudina', 'descripcion' => 'Comprimido 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lamivudina', 'descripcion' => 'Jarabe o Solución oral 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ledipasvir + Sofosbuvir', 'descripcion' => 'Comprimido 90 mg + 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Levofloxacina', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Levofloxacina', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Linezolid', 'descripcion' => 'Comprimido 600 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lopinavir + Ritonavir', 'descripcion' => 'Comprimido 200 mg + 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Lopinavir + Ritonavir', 'descripcion' => 'Solución oral 80 mg + 20 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Meropenem', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Minociclina', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Moxifloxacina', 'descripcion' => 'Comprimido 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nevirapina', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nevirapina', 'descripcion' => 'Suspensión 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nitrofurantoína', 'descripcion' => 'Comprimido 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Nitrofurantoína', 'descripcion' => 'Suspensión 25 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ofloxacina', 'descripcion' => 'Comprimido 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ofloxacina', 'descripcion' => 'Comprimido 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Oseltamivir', 'descripcion' => 'Cápsula 75 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Oseltamivir', 'descripcion' => 'Suspensión 12 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Oseltamivir', 'descripcion' => 'Suspensión 30 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Piperacilina + Tazobactam', 'descripcion' => 'Inyectable 4 g/500 mg', 'unidad_medida' => 'g', 'observaciones' => null],
            ['nombre' => 'Pirazinamida', 'descripcion' => 'Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Raltegravir (potásico)', 'descripcion' => 'Comprimido 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rifampicina', 'descripcion' => 'Cápsula o Comprimido 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rifampicina', 'descripcion' => 'Cápsula o Comprimido 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rifampicina', 'descripcion' => 'Suspensión 100 mg/5 ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rifampicina + Isoniazida (INH)', 'descripcion' => 'Comprimido 300 mg + 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rifampicina, Clofazimina, Dapsona', 'descripcion' => 'Comprimido 300 mg + 100 mg + 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rifampicina, Clofazimina, Dapsona', 'descripcion' => 'Comprimido 300 mg + 50 mg + 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rifampicina, Dapsona', 'descripcion' => 'Comprimido 300 mg + 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Rifampicina, Dapsona', 'descripcion' => 'Comprimido 300 mg + 50 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Ritonavir', 'descripcion' => 'Cápsula blanda 100 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Sofosbuvir', 'descripcion' => 'Comprimido 400 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Suero Antiescorpiónico', 'descripcion' => 'Inyectable Según disponibilidad', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Suero Antilatrodectus', 'descripcion' => 'Inyectable Según disponibilidad', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Suero Antiofídico Botrópico Crotálico', 'descripcion' => 'Inyectable Según disponibilidad', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Suero Antiofídico Botrópico Laquésico', 'descripcion' => 'Inyectable Según disponibilidad', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Suero Antirrábico (heterólogo)', 'descripcion' => 'Inyectable Según disponibilidad', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Tenofovir disoproxilo', 'descripcion' => 'Comprimido 245 mg (Equiv. a 300 mg como fumarato)', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tenofovir disoproxilo + Efavirenz + Lamivudina', 'descripcion' => 'Comprimido 300 mg + 600 mg + 300 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Tetraciclina', 'descripcion' => 'Cápsula o Comprimido 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Toxoide tetánico adsorbido', 'descripcion' => 'Inyectable 120 UI/ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna antiamarílica', 'descripcion' => 'Inyectable Norma PAI (10 dosis)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna antiamarílica', 'descripcion' => 'Inyectable Norma PAI (20 dosis)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna antiamarílica', 'descripcion' => 'Inyectable Norma PAI (5 dosis)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna antihepatitis B', 'descripcion' => 'Inyectable Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna antineumococo (13 valente)', 'descripcion' => 'Inyectable Norma PAI (Unidosis)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna antipoliomielítica bivalente', 'descripcion' => 'Solución oral Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna antipoliomielítica inactivada', 'descripcion' => 'Inyectable Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna Antirotavírica', 'descripcion' => 'Solución oral Norma PAI (Unidosis)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna Antirotavírica', 'descripcion' => 'Solución oral Norma PAI Multidosis', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna Antirrábica', 'descripcion' => 'Inyectable 1 UI/ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna Antirrábica de uso Humano (Cultivo Celular)', 'descripcion' => 'Inyectable 2,5 U.I./0,5 ml', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna BCG', 'descripcion' => 'Inyectable Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna contra COVID-19', 'descripcion' => 'Inyectable Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna contra Influenza (Adulto)', 'descripcion' => 'Inyectable Norma PAI (10 dosis)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna contra Influenza (Pediátrica)', 'descripcion' => 'Inyectable Norma PAI (10 dosis)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna cuadrivalente recombinante contra el Virus del Papiloma Humano', 'descripcion' => 'Inyectable Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna doble dT (difteria, Tétanos)', 'descripcion' => 'Inyectable Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna pentavalente (DPT + Hep. B + H. Influenzae B)', 'descripcion' => 'Inyectable Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna SR (Sarampión, Rubeola)', 'descripcion' => 'Inyectable Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna SRP (Sarampión, Rubeola, Paperas)', 'descripcion' => 'Inyectable Norma PAI (Unidosis)', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna SRP (Sarampión, Rubeola, Paperas)', 'descripcion' => 'Inyectable Norma PAI Multidosis', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Vacuna Triple DPT (Difteria, Pertusis, Tétanos)', 'descripcion' => 'Inyectable Norma PAI', 'unidad_medida' => 'UI', 'observaciones' => null],
            ['nombre' => 'Valganciclovir', 'descripcion' => 'Comprimido 450 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Vancomicina', 'descripcion' => 'Inyectable 500 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Voriconazol', 'descripcion' => 'Polvo para inyectable 200 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Zidovudina', 'descripcion' => 'Inyectable 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Zidovudina', 'descripcion' => 'Suspensión oral 10 mg/ml', 'unidad_medida' => 'mg', 'observaciones' => null],
            ['nombre' => 'Zidovudina + Lamivudina', 'descripcion' => 'Comprimido 300 mg + 150 mg', 'unidad_medida' => 'mg', 'observaciones' => null],
        ];
    }
}
